from TaskManagementAPI.env_loader import (
    DEBUG,
    SECRET_KEY,
    SQLALCHEMY_TRACK_MODIFICATIONS,
    SQLALCHEMY_DATABASE_URI,
    HOST,
    PORT
)




class Config:
    PORT=PORT
    HOST=HOST
    DEBUG = DEBUG
    SECRET_KEY = SECRET_KEY
    SQLALCHEMY_TRACK_MODIFICATIONS = SQLALCHEMY_TRACK_MODIFICATIONS
    SQLALCHEMY_DATABASE_URI = SQLALCHEMY_DATABASE_URI