"""empty message

Revision ID: 1e1d1a0ad1a4
Revises: bc2f43171291
Create Date: 2023-11-21 00:59:00.770717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e1d1a0ad1a4'
down_revision = 'bc2f43171291'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('otp', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('is_otp_used', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_otp_used')
    op.drop_column('user', 'otp')
    # ### end Alembic commands ###
