"""empty message

Revision ID: e3223ea1619a
Revises: 
Create Date: 2023-11-20 22:59:48.501091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3223ea1619a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('org',
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('org_uid', sa.String(), nullable=False),
    sa.Column('org_name', sa.String(), nullable=False),
    sa.Column('org_email', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('org_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('org')
    # ### end Alembic commands ###
